version: "3"

services:

  nextjs:
    build: .
    container_name: nextjs-app
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./prisma/prisma/dev.db:/app/prisma/prisma/dev.db

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nextjs